### ISSUE TITLE
remove conftest imports

### ISSUE THREAD

**Issue by g-k** [mozilla-services/pytest-services#119]
- [ ] move client config options into per service conftest.py files?
- [ ] convert global client vars into calls that setup and return the relevant client or a cached one (on subsequent calls e.g. `aws_client().foo()` instead of `aws_client.foo()` in resources.py files
  * TODO: make sure the `client()` functions can import the pytest config to get their config values or use the builtin pytest config fixture

refs https://github.com/mozilla-services/pytest-services/issues/116#issuecomment-391085890

**Comment by hwine** [comment]
afaik, it's okay to use "``from conftest import my_special_foo``". The problematic usage is "``import conftest``" or "``from conftest import pytest_magic``". So I don't think we're too far off.
