### ISSUE TITLE
Add ability to mark a resource as exempt from a certain test

### ISSUE THREAD

**Issue by ajvb** [mozilla-services/pytest-services#18]
Add ability to mark a resource as exempt from a certain test along side an optional reason and expiration date. Should include the ability to mark a resource as exempt from more than one test and from all tests.

Would also be nice to add the ability to pull in suppressed checks on resources from trusted advisor (http://botocore.readthedocs.io/en/latest/reference/services/support.html#Support.Client.describe_trusted_advisor_check_result).  

edit (g-k): 

Moved the trusted advisor check to https://github.com/mozilla-services/pytest-services/issues/37

Planning to do this similar to the severity config #28 i.e.

- [ ] add a conf file
- [ ] for each exemption add an xfail marker in `pytest_runtest_setup` with reason, expiration time, and the conf filename and line number
- [ ] add exemptions section to readme

Markers will be serialized and included in the test metadata.
It will need to match on resource and test names.

**Comment by g-k** [comment]
For dev, I've hidden failures by suppressing tracebacks with `--tb=no`.

But tracking exemptions or exceptions is problem.

We can mark expected failures like so:

```python
# content of test_expectation.py
import pytest
@pytest.mark.parametrize("test_input,expected", [
    ("3+5", 8),
    ("2+4", 6),
    pytest.param("6*9", 42,
                 marks=pytest.mark.xfail),
])
def test_eval(test_input, expected):
    assert eval(test_input) == expected
```

https://docs.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions

But including them in the test file was painful, since it mixed test logic and data. 

We could come up with an exceptions file format and a way to load them from an env var or CLI args.

**Comment by ajvb** [comment]
>But including them in the test file was painful, since it mixed test logic and data.

Absolutely. Plus, it's data that I believe is pretty sensitive so we'll want to keep it out of this repo.

>We could come up with an exceptions file format and a way to load them from an env var or CLI args.

I like this. I haven't found a mechanism for doing this built into `pytest`, but shouldn't be too hard to write a custom test decorator or do it all within `pytest_runtest_makereport`.

**Comment by g-k** [comment]
Options for which resource name to match on:

* ~~the parametrized argument name (e.g. 'ec2_instance')~~ not helpful
* the test parametrize id (requires `@parametrize` decorator, ids are optional and vary by test, for tests with multiple resources only match the one used in the test id)
* some other getter on the fixture value (we tried this before and it sucked, but it might work this time, also would need to answer: when multiple fixtures exist do we match any or all of them?)

**Comment by g-k** [comment]
Planning to:

* use the parametrize test ids (after some digging they are exposed as `item._genid`) If desirable we can standardize the test ids in the relevant pytest hook and maybe use type hints.
* warn and not add the xfail marker when the parametrize marker isn't found
* require exact matches on the unparametrized test name and resource ids in the config for now (like the severity config), but we could make this fuzzier in the future (i.e. expect failures for all test names or ids matching a regex, but the rules would need some sort of precedence in case multiple matched)
