### ISSUE TITLE
Fix bug with rds db security groups

### ISSUE THREAD

**Issue by g-k** [mozilla-services/pytest-services#27]
@ajvb reports that the wrong security groups aren't being passed as params.

We could disable the test for now and audit the security groups directly.

**Comment by ajvb** [comment]
`test_rds_db_instance_not_publicly_accessible_by_vpc_sg.py` seems to be working perfectly, but `test_rds_db_instance_not_publicly_accessible_by_rds_db_sg.py` seems to be broken.

We should be able to get what we want by using just `test_rds_db_security_group_does_not_grant_public_access.py` and `test_rds_db_instance_not_publicly_accessible_by_vpc_sg.py`.

Opening up a PR.
