### ISSUE TITLE
Pick format for aws CLI args with multiple values (profiles, regions, and required tags)

### ISSUE THREAD

**Issue by g-k** [mozilla-services/pytest-services#31]
* multiple invocations / what we currently have e.g. `--aws-require-tags Name --aws-require-tags Type --aws-require-tags App --aws-require-tags Stack`. This is verbose but allows values containing commas. We'd probably want to rename to use singular nouns.
* CSV values e.g. `--aws-require-tags Name,Type,App,Stack` @ajvb them working in https://github.com/mozilla-services/pytest-services/pull/23#discussion_r164831425 This is concise, but we'd need to escape commas somehow (though needing that is probably unlikely).
* multiple values with one invocation and no commas `--aws-require-tags Name Type App Stack` This is concise and doesn't require commas, but I'm not sure it's possible.

**Comment by g-k** [comment]
Let just use CSVs.

**Comment by ajvb** [comment]
Fixed with #33

**Comment by g-k** [comment]
The third option is possible with `nargs='*'`, so I'll make a PR for that and save us writing some commas.
