### ISSUE TITLE
Attach rationale / reason to each test

### ISSUE THREAD

**Issue by ajvb** [mozilla-services/pytest-services#32]
Could do this using test decorators or within the config file

**Comment by g-k** [comment]
+1

The skip and xfail markers takes a reason kwarg: https://docs.pytest.org/en/latest/skipping.html#skipping-test-functions 

We could use docstrings and [a custom marker](https://docs.pytest.org/en/latest/example/markers.html#custom-marker-and-command-line-option-to-control-test-runs) e.g. `@pytest.mark.reason("prevent leaking data")`

Exceptions should have reasons too.
