### ISSUE TITLE
default ignore collector?

### ISSUE THREAD

**Issue by g-k** [mozilla-services/pytest-services#7]
As we add more services and tests we need to add more ignore args so an inverted match (i.e. only things matching) this would be useful.

Could be implemented as a custom default ignore collector.

**Comment by g-k** [comment]
@ajvb has a nice workaround of just including the directories to collect https://github.com/mozilla-services/pytest-services/blob/9b63879652728fa10f11cac427ae124014c98085/Makefile#L12

**Comment by ajvb** [comment]
@g-k Along side that, locally I've been using this for auditing security groups:

```
aws-sg: check_venv
        pytest \
                aws/ec2/test_ec2_security_group_in_use.py \
                aws/ec2/test_ec2_security_group_opens_all_ports.py \
                aws/ec2/test_ec2_security_group_opens_all_ports_to_all.py \
                aws/ec2/test_ec2_security_group_opens_all_ports_to_self.py \
                aws/rds/test_rds_db_security_group_does_not_grant_public_access.py \
                aws/rds/test_rds_db_instance_not_publicly_accessible_by_vpc_sg.py \
                --aws-profiles $(AWS_PROFILE) --json=results-sg-$(AWS_PROFILE)-$(TODAY).json
```

It's pretty fragile, but also works perfectly and is super easy to modify 😸

**Comment by g-k** [comment]
Nice! Feel free to add that target for that.  r+ in advance

**Comment by g-k** [comment]
Closing this in favor of AJ's "including files explicitly" approach.
