### ISSUE TITLE
Create a configurable test around discovering inactive accounts

### ISSUE THREAD

**Issue by ajvb** [mozilla-services/pytest-services#98]
Create a test that will download the credential report and look for users that haven't been used in X amount of time, configurable within the config.yaml file.

**Comment by ckolos** [comment]
+1 if you add an ability to lock based on that age, i.e. report *and* act if flag is set.

**Comment by jvehent** [comment]
We might want a condition to ignore users that are in a specific group. We use that to deactivate access without deleting accounts.

**Comment by g-k** [comment]
Not sure if we want to address this here, but there's a larger issue around making pytest-services aware of differences over time and using that data to report trends or detect suspicious patterns.

Specifically we'd want to cover:

* tests pass, but the change is interesting/suspicious (e.g. # of new admin users in prod doubles or a valid new admin user is created out of hours)
* config enters invalid state (i.e. tests would fail) between pytest runs 

Possible implementations:

* ingest report JSON files and report trends 
* ingest cloudtrail logs, reconstruct the config state, test state after each transition, and report failures for given points in time
  * or enable [AWS Config](https://aws.amazon.com/config/) and support running tests in lambdas

**Comment by ajvb** [comment]
@ckolos +1 - will probably implement that separate from `pytest-services` but I'd love to have that.

@jvehent So we move users to a specific group but keep their access keys and/or login profile?


@g-k I absolutely want what you are describing, and it's interesting that the second piece ("config enters invalid state between pytest runs") points to a potentially fundamental problem with `pytest-services` (for AWS). I like the idea of writing some tooling that `ingest report JSON files and report trends`. In regards to ingesting cloudtrail logs and reconstructing the config state, I'd be more inclined to look at that as something we should do continuously rather than in the current "nightly batch jobs" style of `pytest-services`.
